<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class IssueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('issues')->insert([
            [
                'issue_name' => 'FOLDER_BELONG_SUBJECTS',
				'external_issue_name' => NULL,
				'issue_description' => 'Do all People belong to FOLDER',
				'issue_error_message' => '<p class="text-danger">Please click "Edit" above the Subject photo and nominate their correct Class/Group.</p>',
				'approval_status_id' => 3,
				'issue_category_id' => 1,
				'is_proceed_confirm' => 0,
            ],
            [
                'issue_name' => 'FOLDER_SPELL_SUBJECT',
				'external_issue_name' => NULL,
				'issue_description' => 'Are all People spelt correctly?',
				'issue_error_message' => '<p class="text-danger">Please click "Edit" above the Subject photo and correct the spelling. You must correct the spelling and answer "Yes" to this question before proceeding.</p>',
				'approval_status_id' => 3,
				'issue_category_id' => 1,
				'is_proceed_confirm' => 1,
            ],
            [
                'issue_name' => 'SUBJECTS_CORRECT_PHOTO',
				'external_issue_name' => NULL,
				'issue_description' => 'Do all People have the correct photo?',
				'issue_error_message' => '<p class="text-danger">Please click "Edit" above the Subject photo and tag the photo as incorrect.</p>',
				'approval_status_id' => 3,
				'issue_category_id' => 1,
				'is_proceed_confirm' => 0,
            ],
            [
                'issue_name' => 'SUBJECTS_ACCOUNTED',
				'external_issue_name' => NULL,
				'issue_description' => 'Are all People accounted for?',
				'issue_error_message' => '<label for="subject_missing_names" class="form-control-label text-danger">Please type out the names of missing People. Separate multiple names with a comma.</label><textarea class="form-control" name="subject_missing_names" id="subject_missing_names" rows="5"></textarea>',
				'approval_status_id' => 3,
				'issue_category_id' => 1,
				'is_proceed_confirm' => 0,
            ],
            [
                'issue_name' => 'FOLDER_CORRECTED',
				'external_issue_name' => 'Issue Recorded for Correction',
				'issue_description' => 'Have all of the issues on this page been recorded for correction?',
				'issue_error_message' => '<label for="subject_general_issue_text" class="text-danger">Please type out any remaining issues.</label><textarea id="subject_general_issue_text" name="subject_general_issue_text" class="form-control" rows="5"></textarea>',
                'approval_status_id' => 3,
				'issue_category_id' => 1,
				'is_proceed_confirm' => 0,
            ],             
            [
                'issue_name' => 'FOLDER_NAME_CHANGE',
                'external_issue_name' => 'Class Name',
                'issue_description' => 'Folder name has been changed.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],           
            [
                'issue_name' => 'SUBJECT_MISSING_NAMES',
                'external_issue_name' => NULL,
                'issue_description' => 'subjects missing',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'GENERAL_ISSUES',
                'external_issue_name' => 'General Issue ',
                'issue_description' => 'general issues',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],  
            [
                'issue_name' => 'DEPUTY',
                'external_issue_name' => 'Deputy',
                'issue_description' => 'deputy',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'PRINCIPAL',
                'external_issue_name' => 'Principal',
                'issue_description' => 'principal',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'TEACHER',
                'external_issue_name' => 'Teacher',
                'issue_description' => 'teacher',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'TRADITIONAL PHOTO',
                'external_issue_name' => NULL,
                'issue_description' => 'traditional photo subject row positions',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 4,
                'is_proceed_confirm' => NULL,
            ],               
            [
                'issue_name' => 'GROUP_COMMENTS',
                'external_issue_name' => NULL,
                'issue_description' => 'Comments/Notes',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 3,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'GROUP_NAMED',
                'external_issue_name' => NULL,
                'issue_description' => 'Have you named each Person in the Group Photo?',
                'issue_error_message' => '<p class="text-danger">Please type out each Persons name according to their row position. You can add more rows if needed.</p>',
                'approval_status_id' => 3,
                'issue_category_id' => 3,
                'is_proceed_confirm' => NULL,
            ],       
            [
                'issue_name' => 'SUBJECT_ISSUE_SPELLING',
                'external_issue_name' => 'Spelling',
                'issue_description' => 'Spelling mistake in FULLNAME',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_JOBTITLE_SALUTATION',
                'external_issue_name' => 'Job Title & Salutation',
                'issue_description' => 'Add or modify the Job Title and Salutation of FULLNAME.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_SALUTATION',
                'external_issue_name' => 'Salutation',
                'issue_description' => 'Add or modify the Salutation of FULLNAME.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_JOBTITLE',
                'external_issue_name' => 'Job Title',
                'issue_description' => 'Add or modify the Job Title of FULLNAME.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_PICTURE',
                'external_issue_name' => 'Picture',
                'issue_description' => 'Wrong picture for FULLNAME',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_CLASS',
                'external_issue_name' => 'Class',
                'issue_description' => 'FULLNAME does not belong in this Class/Group.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_ISSUE_LEFT_SCHOOL',
                'external_issue_name' => 'Left School',
                'issue_description' => 'FULLNAME has left this School.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],            
            [
                'issue_name' => 'SUBJECT_REMOVE_PICTURE',
                'external_issue_name' => 'Remove Picture',
                'issue_description' => 'Please remove picture of FULLNAME for reasons such as infringement or child protection.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],          
            [
                'issue_name' => 'SUBJECT_ABSENT',
                'external_issue_name' => 'Absent',
                'issue_description' => 'FULLNAME was absent on photo-day.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],        
            [
                'issue_name' => 'SUBJECT_ISSUE_PREFIX_SUFFIX',
                'external_issue_name' => 'Prefix & Suffix',
                'issue_description' => 'Add or modify the Prefix and Suffix of FULLNAME.',
                'issue_error_message' => NULL,
                'approval_status_id' => 3,
                'issue_category_id' => 2,
                'is_proceed_confirm' => NULL,
            ],
        ]);
    }
}
