<x-photography.portrait
    id="{{$imageId}}"
    img="{{$image}}"
    name="{{$name}}"
    folderName="{{$folderName}}"
    landscape="{{$landscape}}"
    hasImage="{{$hasImage}}"
    isLightbox="{{$isLightbox}}"
    isUploaded="{{$isUploaded}}"
/>
