export const NAV_TABS = {
    HOME: 'Home',
    FRANCHISE_DASHBOARD: 'Dashboard',
    PHOTOGRAPHY: 'Photography',
    PORTRAITS: 'Portraits',
    GROUP: 'Group',
    SPECIAL_EVENTS: 'Special Events',
    PROMO_PHOTOS: 'Promo Photos',
    PROOFING: 'Proofing',
    MANAGE_USERS: 'Manage Users',
    REPORTS: 'Reports',
    EMAILS: 'Emails',
    ORDER: 'Ordering',
    CONFIG_SCHOOL: 'School Config',
    APP_SETTINGS: 'App Settings',
}
